/*
Problem :
You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible subsequences of 'STR'.
A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.


input : abc

Output :
{a}, {ab} {abc} {ac} {b} {bc} {c}

*/

#include<iostream>
#include<vector>
using namespace std;

void solve(string str,string output,int index,vector<string>& ans)
{
// base case
if(index>=str.length())
{
    if(output.length()>0)
    {
     ans.push_back(output);
    }
     return ;
}

//excued
solve(str,output,index+1,ans);

//inlude call
char element=str[index];
output.push_back(element);
solve(str,output,index+1,ans);


}

vector<string> sub_string(string str )
{
    vector<string> ans;
    string output="";
    int index=0;
    solve(str,output,index,ans);
    return ans;

}

int main()
{
    string str="har";
    vector<string> ans=sub_string(str);
 
      for(const auto& subset: ans)
      {
        cout << "{ ";
        for (char num : subset) {
            cout << num << " ";
        }
        cout << "}" << endl;
    }

}